---
title: "NeuronMotif"
author: "Zheng Wei"
date: "`r Sys.Date()`"
output: 
    html_document:
        df_print: paged
#        toc: true
#        toc_float: true
#        fig_height: 3.5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



# Motifs of neurons in layer 3 (Basset model)

```{r message=FALSE,warning=FALSE}


tomtom<- list.files('./','tomtom.tsv',recursive=T)
meme <-list.files('./','meme',recursive=T)

nmdata <- lapply(1:length(meme), function(i){
    memefile <- meme[[i]]
    lines<- readLines(memefile)
    motifName<-lines[startsWith(lines,'MOTIF')]
    motifName <-strsplit(motifName,' ')[[1]][[2]]
    motifName <- strsplit(motifName,'_')[[1]]
    xxx <- basename(meme[[i]])
    xxx <- strsplit(xxx,'\\.')[[1]][1]

    prefix <- file.path('result',xxx,paste0(xxx,'.out'))
    htmlfile <- file.path(prefix,'tomtom.html')
    pdffile <- file.path(prefix,'tomtom.pdf')
    xmlfile <- file.path(prefix,'tomtom.xml')
    tsvfile <- file.path(prefix,'tomtom.tsv')
    if(!file.exists(htmlfile)){
        htmlfile<-'NA'
    }else{
        htmlfile <- sprintf("<a href='%s'>tomtom.html</a>",htmlfile)
    }
    if(!file.exists(pdffile)){
        pdffile<-'NA'
    }else{
        pdffile <- sprintf("<a href='%s'>tomtom.pdf</a>",pdffile)
    }    
    if(!file.exists(xmlfile)){
        xmlfile<-'NA'
    }else{
        xmlfile <- sprintf("<a href='%s'>tomtom.xml</a>",xmlfile)
    }  
    if(!file.exists(tsvfile)){
        tsvfile<-'NA'
    }else{
        tsvfile <- sprintf("<a href='%s'>tomtom.tsv</a>",tsvfile)
    }  
    memefile <- sprintf("<a href='%s'>tomtom.meme</a>",memefile)
    if(as.numeric(motifName[3])==0){
        motifName[3:4]='NA'
    }
    return(
        c(
            as.integer(as.integer(motifName[1])/12),
            as.integer(motifName[1])%%12,
            motifName[2:4],
            paste0(sprintf('%.2f',as.numeric(motifName[4])/as.numeric(motifName[3]) * 100),'%'),
            htmlfile,
            pdffile,
            memefile,
            tsvfile,
            xmlfile
        )
    )

    
})

    
df <- do.call(rbind,nmdata)

   colnames(df)<-c('Neuron/kernel ID','Shift ID','Sequences count', 'Max activation (M)', 'Consensus sequence activation (C)', 'C/M*100%','HTML','PDF','MEME','TSV','XML') 

knitr::kable(df)
```

